#!/bin/bash

biggest=100
guess=0
guesses=0

number=$(( $$ % $biggest ))

echo "Guess a number between 1 and $biggest"

while [ "$guess" -ne "$number" ]; do
  echo -n "Guess? "; read guess
  
  if [ "$guess" -lt "$number" ]; then
    echo "Too low...."

  elif [ "$guess" -gt "$number" ]; then
    echo "Too high...."
  fi

  guesses=$(( $guesses + 1 ))
done

echo "Correctly found after $guesses guess !!"
exit 0
