#!/bin/bash
# normdate - Normalizes month field in date specifications to three letters.
#   first letter capitalized.
#   exits with 0 if no error

monthNumToName() {
  case $1 in
    1 ) month="Jan"     ;;      2 ) month="Feb"     ;;
    3 ) month="Mar"     ;;      4 ) month="Apr"     ;;
    5 ) month="May"     ;;      6 ) month="Jun"     ;;
    7 ) month="Jul"     ;;      8 ) month="Aug"     ;;
    9 ) month="Sep"     ;;      10 ) month="Oct"    ;;
    11 ) month="Nov"    ;;      12 ) month="Dec"      ;;
    *) echo "$0: Unknown month value $1" >&2
      exit 1
  esac
  return 0
}

# BEGIN MAIN SCRIPT - DELETE OR COMMENT OUT EVERYTHING BELOW THIS LINE IF
#   YOU WANT TO INCLUDE THIS IN OTHER SCRIPTS

# Input validation
if [ $# -ne 3 ]; then
  echo "Usage $0 month day year" >&2
  echo "Formats are August 2 1962 and 8 3 1962" >&2
  exit 1
fi
if [ $3 -le 999 ]; then
  echo "$0: expected 4 digit year value"
  exit 1
fi

if [ -z $(echo $1|sed -e 's/[[:digit:]]//g') ]; then
  monthNumToName $1
else
  # Normalize first three letters, first upper and then lowercase
  month="$(echo ${1:0:1} | tr '[:lower:]' '[:upper:]')"
  month="$month$(echo ${1:1:2} | tr '[:upper:]' '[:lower:]')"
fi

echo "$month" $2 $3

exit 0
