#!/bin/bash

OLDIFS=$IFS
IFS=":"
count=0     ; nonex=0

for directory in $PATH; do
  if [ -d "$directory" ]; then
    for cmd in "$directorty"/*; do
      if [ -x "$cmd" ]; then
        count=$(( $count + 1 ))
      else
        nonex=$(( $nonex + 1 ))
      fi
    done
  fi
done

IFS=$OLDIFS

echo "$count commands, and $nonex entries that weren't executables"
exit 0
